### ISSUE TITLE
What about replacing underscore with Lodash?

### ISSUE THREAD

**Issue by ghost** [ololoepepe/ololord.js#5]
Lodash is a lighter drop-in replacement for Underscore. It's worth it

**Comment by ghost** [comment]
Also  https://github.com/lodash/babel-plugin-lodash

**Comment by ololoepepe** [comment]
At the time I was actively developing the project, Lodash seemed to me an overkill with all it's lots of features. Maybe, some day I will use it, but I believe that will not affect anything much.

**Comment by ghost** [comment]
Thank you for your response
