### ISSUE TITLE
Project future?

### ISSUE THREAD

**Issue by ghost** [ololoepepe/ololord.js#7]

**Comment by ololoepepe** [comment]
@kvrlk I do have some plans on completely rewriting the project using Postgres on the back end and React on the front end, and also creating Docker image(s). The question remains - when that will happen. Most certainly NOT in the next 6 months.

**Comment by ghost** [comment]
@ololoepepe Thank you for the response. <3
I want to help!!!

**Comment by ololoepepe** [comment]
@kvrlk Any help is highly appreciated. I'll let you know. Please, do not close this issue so that when I start working on the project, I'll see it and contact you.

**Comment by ololoepepe** [comment]
Although I just started working on the project (again), I'm closing this issue as it's author has deleted his account.
